### ISSUE TITLE
Consider `'key := value` instead of `'key /= value` 

### ISSUE THREAD

**Issue by guersam** [fomkin/levsha#10]
Is there a specific reason that you chose `'key /= value` in the DSL? It's a bit confusing to me because `/=` means _not equal_ in some languages like Haskell.

**Comment by guersam** [comment]
Just read the korolev doc section mentioning `:=`, but still a bit confusing.

**Comment by fomkin** [comment]
It has historical reason. Levsha/Korolev is a continuation of Moorka, DSL was inherited. https://github.com/tenderowls/moorka. Moorka was running on a client with Scala.js so it was better to using properties instead of attributes. `:=` was for properties and `/=` for attributes, and of course `:=` was used oftener. Levsha/Korolev making server-side rendering, and it is a reason to use attributes instead of properties, so `/=` now using oftener.

**Comment by guersam** [comment]
Thanks for the explanation. I'm not 100% convinced of `/=` for the above reason and maybe I could suggest `%=`, `^=`  or something else , but it's not a deal breaker. Great work!
